name: rommyandrew
favicon: null
layout_spectrum: 0.5840453784912825
typography_spectrum: 0.19913989258930087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee0db'
    - '#363030'
    - '#a7856a'
    - '#346488'
    - '#4c8db3'
  brandStrength: 0.8141296082176268
  lightness: 0.4233533442020416
  saturation: 0.9159599386621267
  rhythmicContrast: 0.35625638300552964
purpose: []
