layout_spectrum: 0.08446966926567256
typography_spectrum: 0.8161404088605195
color:
  brandColors:
    - '#F1E9C7'
    - '#493D56'
    - '#E89B73'
    - '#B26B54'
    - '#BEB2BE'
  brandStrength: 0.8758306710515171
  lightness: 0.3307871788274497
  saturation: 0.20488178986124694
  rhythmicContrast: 0.07309592817910016
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Rommy Andrew '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Rommy Andrew '
description: Tide Shadows
purpose: []
