favicon: null
name: rommyandrew
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6917562
  brandStrength: 0.1875
  lightness: 0.1935484
  brandColors:
    - '#CEDAB3'
    - '#77554A'
    - '#6FA286'
    - '#77C5B4'
    - '#1F656D'
  rhythmicContrast: 0.4820789
typography_spectrum: 0.29332
layout_spectrum: 0.5268817
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
