name: rommyandrew
favicon: null
layout_spectrum: 0.33484
typography_spectrum: 0.1991398925893009
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f2e27'
    - '#639999'
    - '#eae8dc'
    - '#bdb7a9'
    - '#984e1d'
  brandStrength: 0.3125
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
